# Generated by Django 5.0.6 on 2024-05-10 15:29

import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='times',
            options={'verbose_name': 'Время', 'verbose_name_plural': datetime.datetime(2024, 5, 10, 20, 29, 23, 893636)},
        ),
    ]
